CREATE TABLE `enquiries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`enquiryId` varchar(20) NOT NULL,
	`dateOfEnquiry` date NOT NULL,
	`time` varchar(10),
	`communicationChannel` varchar(50),
	`receivedBy` varchar(100),
	`clientName` varchar(255) NOT NULL,
	`clientType` varchar(50),
	`nationality` varchar(100),
	`email` varchar(320),
	`phoneNumber` varchar(50),
	`preferredContactMethod` varchar(50),
	`languagePreference` varchar(50),
	`serviceRequested` varchar(255),
	`shortDescription` text,
	`urgencyLevel` varchar(20),
	`clientBudget` decimal(15,2),
	`potentialValueRange` varchar(50),
	`expectedTimeline` varchar(100),
	`referralSourceName` varchar(255),
	`competitorInvolvement` varchar(20),
	`competitorName` varchar(255),
	`assignedDepartment` varchar(100),
	`suggestedLeadLawyer` varchar(100),
	`currentStatus` varchar(50) NOT NULL DEFAULT 'Pending',
	`nextAction` text,
	`deadline` date,
	`firstResponseDate` date,
	`firstResponseTimeHours` decimal(10,2),
	`meetingDate` date,
	`proposalSentDate` date,
	`proposalValue` decimal(15,2),
	`followUpCount` int DEFAULT 0,
	`lastContactDate` date,
	`conversionDate` date,
	`engagementLetterDate` date,
	`matterCode` varchar(20),
	`paymentStatus` varchar(50),
	`invoiceNumber` varchar(100),
	`lostReason` text,
	`internalNotes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `enquiries_id` PRIMARY KEY(`id`),
	CONSTRAINT `enquiries_enquiryId_unique` UNIQUE(`enquiryId`)
);
--> statement-breakpoint
CREATE TABLE `payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`enquiryId` int NOT NULL,
	`matterCode` varchar(20) NOT NULL,
	`paymentTerms` text,
	`paymentStatus` varchar(50) NOT NULL DEFAULT 'Not Started',
	`totalAmount` decimal(15,2),
	`amountPaid` decimal(15,2) DEFAULT '0',
	`amountOutstanding` decimal(15,2),
	`retainerPaidDate` date,
	`retainerAmount` decimal(15,2),
	`midPaymentDate` date,
	`midPaymentAmount` decimal(15,2),
	`finalPaymentDate` date,
	`finalPaymentAmount` decimal(15,2),
	`paymentNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `enquiries` ADD CONSTRAINT `enquiries_createdBy_users_id_fk` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `payments` ADD CONSTRAINT `payments_enquiryId_enquiries_id_fk` FOREIGN KEY (`enquiryId`) REFERENCES `enquiries`(`id`) ON DELETE no action ON UPDATE no action;